//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package dev.datlin.configuration;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColumnType")
public class ColumnType {

    @XmlAttribute(name = "column", required = true)
    protected String column;

    @XmlAttribute(name = "primary-key")
    protected Boolean primaryKey;

    /**
     * Gets the value of the column property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setColumn(String value) {
        this.column = value;
    }

    /**
     * Gets the value of the primaryKey property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setPrimaryKey(Boolean value) {
        this.primaryKey = value;
    }

}
