//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package dev.datlin.configuration;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dev.datlin.configuration package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dev.datlin.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatlinConfiguration }
     * 
     * @return
     *     the new instance of {@link DatlinConfiguration }
     */
    public DatlinConfiguration createDatlinConfiguration() {
        return new DatlinConfiguration();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     * @return
     *     the new instance of {@link ConnectionType }
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link TableType }
     * 
     * @return
     *     the new instance of {@link TableType }
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link QueryType }
     * 
     * @return
     *     the new instance of {@link QueryType }
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link ProcedureType }
     * 
     * @return
     *     the new instance of {@link ProcedureType }
     */
    public ProcedureType createProcedureType() {
        return new ProcedureType();
    }

    /**
     * Create an instance of {@link ColumnType }
     * 
     * @return
     *     the new instance of {@link ColumnType }
     */
    public ColumnType createColumnType() {
        return new ColumnType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     * @return
     *     the new instance of {@link ParameterType }
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link SqlContentType }
     * 
     * @return
     *     the new instance of {@link SqlContentType }
     */
    public SqlContentType createSqlContentType() {
        return new SqlContentType();
    }

}
